name: Accessibility Review
on: [workflow_call, workflow_dispatch]
jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install axe-playwright-python typer render-engine==2023.7.4a7
          playwright install --with-deps
      - name: get date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - name : Run accessibility tests
        run: |
          python a11y.py --output "accessibility-report-${{steps.date.outputs.DATE}}-${{github.run_id}}.txt"
          cat "accessibility-report-${{steps.date.outputs.DATE}}-${{github.run_id}}.txt" >> $GITHUB_STEP_SUMMARY

      - uses: actions/upload-artifact@v3
        with:
          name: accessibility-report-${{steps.date.outputs.DATE}}-${{github.run_id}}.txt
          path: accessibility-report-${{steps.date.outputs.DATE}}-${{github.run_id}}.txt 
